import { prisma } from "@/server/db";

/**
 * Telegram link data layer. Per-user scoped where a userId is known (settings
 * actions); the webhook path (linkChatByCode) is keyed by the one-time code,
 * which is the only thing Telegram echoes back — there is no authenticated
 * user on the webhook, so the code IS the capability.
 */

/**
 * Store a fresh one-time link code on the user. Any existing chat link is kept
 * (re-linking only swaps the chat when a new /start <code> arrives). The code
 * is generated by the caller (crypto-random) and passed in, so this stays I/O
 * only — no randomness to make unit tests flaky.
 */
export function setLinkCode(userId: string, code: string): Promise<unknown> {
  return prisma.user.update({
    where: { id: userId },
    data: { telegramLinkCode: code },
  });
}

/**
 * Webhook link step: find the user holding `code`, set their telegramChatId and
 * null the code (one-time use). Returns true iff a user matched. Uses
 * updateMany so a non-matching code is a no-op (count 0) rather than a throw,
 * keeping the webhook on its no-throw path.
 */
export async function linkChatByCode(
  code: string,
  chatId: string,
): Promise<boolean> {
  const result = await prisma.user.updateMany({
    where: { telegramLinkCode: code },
    data: { telegramChatId: chatId, telegramLinkCode: null },
  });
  return result.count > 0;
}

/** Unlink: clear both the chat id and any pending code for this user. */
export function unlinkTelegram(userId: string): Promise<unknown> {
  return prisma.user.update({
    where: { id: userId },
    data: { telegramChatId: null, telegramLinkCode: null },
  });
}

/**
 * All users with a linked chat, for the daily reminder cron. Selects only what
 * the cron needs (id, chatId, locale) — no broad user reads.
 */
export function listLinkedUsers(): Promise<
  { id: string; telegramChatId: string | null; locale: string }[]
> {
  return prisma.user.findMany({
    where: { telegramChatId: { not: null } },
    select: { id: true, telegramChatId: true, locale: true },
  });
}
